# Generated by Django 6.0.2 on 2026-02-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт работы (лет)')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('services', models.ManyToManyField(related_name='masters', to='services.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
