# Generated by Django 6.0.2 on 2026-02-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits_used', models.PositiveIntegerField(default=0, verbose_name='Использовано посещений')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплаченная сумма')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_until', models.DateField(verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('frozen_until', models.DateField(blank=True, null=True, verbose_name='Заморожен до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
            ],
            options={
                'verbose_name': 'Абонемент клиента',
                'verbose_name_plural': 'Абонементы клиентов',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название абонемента')),
                ('visits_total', models.PositiveIntegerField(verbose_name='Количество посещений')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Срок действия (дней)')),
                ('max_freeze_days', models.PositiveIntegerField(default=0, verbose_name='Макс. дней заморозки')),
                ('available_days', models.CharField(blank=True, max_length=100, verbose_name='Доступные дни')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'План абонемента',
                'verbose_name_plural': 'Планы абонементов',
            },
        ),
    ]
